### ISSUE TITLE
Module affect on enterprise magento version

### ISSUE THREAD

**Issue by Nehace40** [shipperhq/module-address-autocomplete#13]
We are using your module,
Our magento version is 2.2.6 EE
When we place an order with NegotiableQuote it is affect to checkout, it allows you to add new address while checkout.

**Comment by wsajosh** [comment]
Hi @Nehace40 

I'm not seeing any obvious issues with this module and NegotiableQuote. Please see screen shot, can you elaborate on the issue please.
![Screen Shot 2019-04-11 at 17 17 14](https://user-images.githubusercontent.com/1335244/55996854-47b21a80-5c7e-11e9-9957-515a23b76ba4.png)

**Comment by wsaDemo** [comment]
-- Please reply above this line --


Hello, 

Thanks for contacting ShipperHQ. The ShipperHQ offices will be closed
on Monday, May 27th in observance of Memorial Day & Spring Bank
Holiday. We will be monitoring all inboxes for site related outages &
urgent cases. 

The office will re-open on Tuesday, May 27th at 9:30 AM BST.
