### ISSUE TITLE
Address autocomplete extension show error in checkout page.

### ISSUE THREAD

**Issue by Gagan557** [shipperhq/module-address-autocomplete#14]
After using this extension my checkout page  not working. Checkout page show blank no options show to fill form in checkout page.

![Screenshot (269)](https://user-images.githubusercontent.com/35591297/60394533-8d76d480-9b43-11e9-9a21-69c4e3e94187.png)

**Comment by wsajason** [comment]
Hi. Can you confirm that the following have been applied?

1. Flush the cache
2. Remove generated file content by deleting contents of:

- 1. var/view_preprocessed
- 2. pub/static/frontend/
- 3. pub/static/adminhtml/
- 4. pub/static/_requirejs/
- 5. var/generation
- 6. var/cache
- 7. var/page_cache

3. If you are in default or production mode, you will need to recompile your code `bin/magento setup:di:compile`

Please also test with the default theme and (if applicable) default checkout as these can adversely affect.

If that does not resolve please confirm the Magento and PHP versions.

**Comment by Gagan557** [comment]
Hi,
I remove all folder in my magento 2.27.  but show same error in my checkout page.
After using  command - bin/magento setup:di:compile
show error in cmd console 

  [ReflectionException]
  Class ShipperHQ\Shipper\Helper\Data does not exist

![Screenshot (280)](https://user-images.githubusercontent.com/35591297/60564499-889d6500-9d7d-11e9-9e37-3d0a77a70860.png)

**Comment by wsajason** [comment]
Thank you for confirming. You will need to ensure that the prerequisites are installed, per [the description](https://github.com/shipperhq/module-address-autocomplete#description):

- https://github.com/shipperhq/module-shipper
- https://github.com/shipperhq/library-shipper
- https://github.com/shipperhq/library-ws
- https://github.com/shipperhq/module-common
- https://github.com/shipperhq/module-logger

Installing module-shipper via Composer should automatically install its dependencies.

**Comment by Gagan557** [comment]
Thanks it works

**Comment by wsajason** [comment]
Thank you for confirming.
