### ISSUE TITLE
Helper Class not exist

### ISSUE THREAD

**Issue by madhusudan-synoptek** [shipperhq/module-address-autocomplete#15]
There is no helper class

**Comment by wsajason** [comment]
Hi. You will need to ensure that the prerequisites are installed, per the description:

    https://github.com/shipperhq/module-shipper
    https://github.com/shipperhq/library-shipper
    https://github.com/shipperhq/library-ws
    https://github.com/shipperhq/module-common
    https://github.com/shipperhq/module-logger

Installing module-shipper via Composer should automatically install its dependencies.

**Comment by madhusudan-synoptek** [comment]
@wsajason Thanks that works. It is possible that i can only limit the county to US?

**Comment by wsajason** [comment]
That's not a feature of the module, I'm afraid; the address validation will work with all countries. 
If you would like to prevent shipping to other countries this is set within the shipping method's configuration.
