### ISSUE TITLE
Getting the Following error sometimes: Cannot read property 'uid' of undefined

### ISSUE THREAD

**Issue by madhusudan-synoptek** [shipperhq/module-address-autocomplete#16]
![image](https://user-images.githubusercontent.com/47375146/60957510-66c65400-a322-11e9-9595-23dbd6865620.png)

**Comment by wsajason** [comment]
Hi. Have you removed one of the steet address lines? Ordinarily we would expect 2 street address lines there.
Removing the address line would cause that error to occur.

**Comment by madhusudan-synoptek** [comment]
Will this not work with one street lines?

**Comment by wsajason** [comment]
Only the default functionality is supported. If you modify standard Magento behaviour the module will not provide the same experience.

**Comment by madhusudan-synoptek** [comment]
ok thanks

**Comment by madhusudan-synoptek** [comment]
I will do it to 2 column again and check if its working

**Comment by madhusudan-synoptek** [comment]
I did set it to the default value. Disabled the browser cache and tried again. The error was gone but again i had to refresh the page:
![image](https://user-images.githubusercontent.com/47375146/61292843-ec994200-a7ef-11e9-9d39-91a1bff4c784.png)

**Comment by wsajason** [comment]
This issue was for reference only. Please update via #18

**Comment by mohanvsdckap** [comment]
Hi, The fields are auto-populating in the respective fields sometimes and sometimes they don't. when it is not auto-populating there is an error in the console.
`autocomplete.js:139 Uncaught TypeError: Cannot read property 'uid' of undefined` on line autocomplete.js 139.

The total address lines are 3.

not working address: 676 North Saint Clair Street, Chicago, IL, USA.
