### ISSUE TITLE
When loading first time the autosuggestion not working

### ISSUE THREAD

**Issue by parth-synoptek** [shipperhq/module-address-autocomplete#18]
When I load my checkout page for the first time after login the google autocomplete doesn't work.
I have to refresh my page and than this works.
Please Help!!

**Comment by LoganSHQ** [comment]
Hey there!  That's certainly strange behavior.  Can you please test to see if this issue occurs on multiple browsers?

**Comment by madhusudan-synoptek** [comment]
I have tested this in Firefox as well as chrome.
In Firefox it is working fine but in chrome I have to refresh my page again.

**Comment by wsajason** [comment]
Hi. From your description the most likely cause is that the browser is caching the page. Chrome has very heavy caching, which can cause discrepancies such as these. Commonly, cache is more evident during testing, compared with an organic experience.
Please also ensure that you are using the most recent version (currently 20.3.0) as 20.2.1 accounts for Chrome's auto-fill option.
You can verify whether caching has an effect there by enabling the developer toolbar via View > Developer > Developer Tools, navigating to "Network" and enabling the "Disable cache" option.

**Comment by madhusudan-synoptek** [comment]
Hi I have tried the solution and when I saw my console I was getting the following error, and after refreshing the page it works fine:
![image](https://user-images.githubusercontent.com/47375146/61292087-e7d38e80-a7ed-11e9-8697-25e1d1b0e52a.png)

**Comment by wsajason** [comment]
Thank you for the details This is commonly caused by an incorrect quantity of address lines, as seen here: #16 
Please ensure that the default quantity of address lines are used.

**Comment by wsajason** [comment]
Any changes to the core Magento checkout are not supported, I'm afraid. I would recommend discussing with your developer to identify any changes and whether there are options to bypass the browser's cache.
