### ISSUE TITLE
Using search type 'address' instead of 'geocode' to get precise addresses

### ISSUE THREAD

**Issue by ne0nlight** [shipperhq/module-address-autocomplete#19]
Hey guys,

I'd do a pull request, but I am not sure I am doing all that is needed for the proposed change/desired functionality. So we have had a few occurrences where a customer will end up leaving off a street number from an address which in turn ends up causing issues later on with delivery (as you could imagine).

Example;

> Testing Street
> Beverly Hills, CA 90210

Instead of how it should be;

> 123 Testing Street
> Beverly Hills, CA 90210

Looking more into it, and namely here: https://developers.google.com/maps/documentation/javascript/places-autocomplete#add_autocomplete

You are able to select types for the addresses offered, choices being geocode, address, establishment, etc. It states that it uses `address` for "precise" addresses, which I assume would help in what I'm trying to accomplish (valid, full addresses only).

Looking through the code of the ShipperHQ Autocomplete, it appears you guys have chosen to use geocode for most situations, the two spots I seen listed;

/ShipperHQ/AddressAutocomplete/view/frontend/templates/edit.phtml - Line:280
> autocomplete = new google.maps.places.Autocomplete(
> /** @type {!HTMLInputElement} */(document.getElementById('street_1')),
> {types: ['geocode']});

/ShipperHQ/AddressAutocomplete/view/frontend/web/js/autocomplete.js - Line:68
> autocomplete = new google.maps.places.Autocomplete(
> /** @type {!HTMLInputElement} */(this),
> {types: ['geocode']}
> );

I have tried changing these values to `address` to see if it would be the quick and dirty fix I am looking for, but it didn't appear to change anything. 

Any ideas on either how I can get what I am looking for accomplished, or what other than the above I would need to change to alter the method the search is using? 

Thanks as always for the insight!

Jeff

**Comment by ibraheemnabeelfauzi** [comment]
Hey @ne0nlight  we're looking into this and we'll get back to you on it in a few weeks time. We appreciate your patience.

**Comment by ne0nlight** [comment]
Sounds good, appreciate your effort and time!

**Comment by wsajosh** [comment]
We've tested using "address" and found that this didn't return more useful results unfortunately. We have added some enhancements which may help with this issue in subsequent releases. Please open pull request if you find a good solution to this and we will gratefully review it and merge it into the core extension if appropriate
