### ISSUE TITLE
Address Form auto fill not working on IE11

### ISSUE THREAD

**Issue by valeriish** [shipperhq/module-address-autocomplete#2]
**Precondition:**

- User has website registered account.
- Use IE11.

**Steps to reproduce:**

- Login to the website with registered account.
- Go to address book page.
- Click the Add New Address button at the bottom.

**Expected result:**

- Verify Street Address can be auto-complete.
- Verify After selection, fields Zip/Postal Code, State/Province, City, Street Address will update accordingly chosen address.
- Verify allow select the address full address.
![virtualbox_ie11 - win7_24_08_2017_11_21_34](https://user-images.githubusercontent.com/27428461/29657287-ccdf29e4-88bf-11e7-90ad-e3a35368f5c5.png)

 **Actual result:**

- Street Address can be auto-complete but after selection, fields Zip/Postal Code, State/Province, City, and 
- Street Address cannot update accordingly chosen address.
![image-2017-08-11-17-03-09-603](https://user-images.githubusercontent.com/27428461/29657251-bc97eb48-88bf-11e7-9f94-9f148d0126ba.png)

Notes: This issue only happens on IE 11.  This issue doesn't reproduce on Chrome or Firefox

**FIX**
There's an [IE polyfill for the CustomEvent constructor at MDN](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent). Adding CustomEvent to IE and using that instead works.
Insert into
`module-address-autocomplete/src/view/frontend/templates/edit.phtml`

Code: 
```
<script>
    (function () {
        if ( typeof window.CustomEvent === "function" ) return false; //If not IE

        function CustomEvent ( event, params ) {
          params = params || { bubbles: false, cancelable: false, detail: undefined };
          var evt = document.createEvent( 'CustomEvent' );
          evt.initCustomEvent( event, params.bubbles, params.cancelable, params.detail );
          return evt;
         }

        CustomEvent.prototype = window.Event.prototype;

        window.CustomEvent = CustomEvent;
    })();
</script>
```
...

inside `function fillInAddress() `

```
 if(addressType == 'country') {
    document.getElementById(elementId).dispatchEvent(new window.CustomEvent('change'));
}
```

**Comment by wsagen** [comment]
Latest version of address-autocomplete released today includes the fix for this issue. Thanks again for the PR
