### ISSUE TITLE
Autocomplete result box positioning issue

### ISSUE THREAD

**Issue by mohd-amanullah** [shipperhq/module-address-autocomplete#20]
Hi,

I have installed and configured full package module via composer and it's working fine but positioning of autocomplete result box always appearing in bottom of both pages (Add /Edit address book & checkout).

Could you please let me know what can issues behind this?

Thanks!

**Comment by ibraheemnabeelfauzi** [comment]
Hey, @mohd-amanullah could you please include an example screenshot of the positioning of the Autocomplete appearing at the bottom of the pages? 

Thank you.

**Comment by mohd-amanullah** [comment]
Hi,

Please find the screenshot.
![image](https://user-images.githubusercontent.com/61449688/78319288-79ee1380-7584-11ea-9acb-63786f78b190.png)

Thanks!

**Comment by wsadasmit** [comment]
Hi mohd-amanullah, thanks for raising this, I've added it for review. I'll update again here when this is complete.

**Comment by wsajosh** [comment]
Hi @mohd-amanullah 

I can't replicate this. I believe its an issue with the theme on your site. Please ensure you're using the latest version of the module. This fix in particular seems relevant: https://github.com/shipperhq/module-address-autocomplete/commit/3fb96e8bb03811a557a3bb85826e843cdb52fd53

![Screenshot 2020-10-29 at 11 38 49](https://user-images.githubusercontent.com/1335244/97563695-5173ae00-19db-11eb-8623-52e1650cacaa.png)
