### ISSUE TITLE
Customer Account Autocomplete 

### ISSUE THREAD

**Issue by birdman002** [shipperhq/module-address-autocomplete#22]
This functionality seems to be missing some of the functionality that is in the checkout. 
Post Code as well as setting the autocomplete new-password. 

The template that is being used is not the current 2.3.4 template that is being used. 

Seems like this section needs some updating

**Comment by birdman002** [comment]
Hello!
I was comparing the functionality between the cart and the customer account
in regards to the zip code.

It doesnt appear to set the zip code as it does in  js/autocomplete.js
(Line 113-126)  but i may be missing something.

It also doesnt use the config settings for geolocation or long zip codes.


Thanks for responding so quickly.

Best,
Irwin

**Comment by wsajason** [comment]
Hi @birdman002 
Thank you for the details. When adding an address in the customer account the ZIP code will auto-populate.

I have found inconsistencies with the long ZIP and geolocation options, which I have raised with our developers for further investigation.

**Comment by wsajosh** [comment]
Hi @birdman002 

Thanks for raising this issue. I'm about to create a new release which fixes the long zip option. Please update to the latest version if you'd like to use this feature.
