### ISSUE TITLE
API failure can block checkout completely due to disabled street input field

### ISSUE THREAD

**Issue by ProxiBlue** [shipperhq/module-address-autocomplete#28]
If, after API was initiated, but a further API error happens, google maps disables the street input field

Example:

![2021-10-19_14-54](https://user-images.githubusercontent.com/4994260/137875974-81b7b55f-1f2e-4eba-9339-797ffa6ec6ee.png)

This effectively blocks entire store checkout.

This can be reproduced by assigning an API key for a maps API that has not been correctly setup / activated:

![image](https://user-images.githubusercontent.com/4994260/137876226-43c50c1a-389f-44a3-bf8a-0f7b7057d3e6.png)

**Comment by wsajosh** [comment]
@ProxiBlue Thanks for the fix. Its included in the latest release
