### ISSUE TITLE
Address fields are re-ordered in an illogical way: Country is placed after State/Province

### ISSUE THREAD

**Issue by ProxiBlue** [shipperhq/module-address-autocomplete#31]
The default address entry field order is to have:

Street, Country, State, City

which makes sense as State is derived from selection of country

The autocomplete places Country as the last option, after State, which is not a logical flow.

Default magento 2.4.3

![2021-10-27_10-47](https://user-images.githubusercontent.com/4994260/138991517-c5ed86f2-7564-4c39-9741-22bc1a087860.png)

module installed:

![2021-10-27_10-43](https://user-images.githubusercontent.com/4994260/138991548-1b522828-aa97-4934-ae31-c552afe74ae9.png)

**Comment by wsajosh** [comment]
@ProxiBlue Thanks for this. Its in the latest release
