### ISSUE TITLE
Autocomplete not filling in Region/State/Province field in Checkout for Quebec, Canada addresses

### ISSUE THREAD

**Issue by michaelmagemontreal** [shipperhq/module-address-autocomplete#34]
Hi,

As the title says, we are running the module on Magento 2.4.X (many sites on many 2.4 different versions) and run into this issue on all of our installations. Therefore, I do not think the issue is related to Magento versions.

When using the auto complete feature, all address fields get automatically populated based on the selected address. HOWEVER, this is not the case for addresses located in Quebec, Canada. When entering an address located in Quebec, all fields get automatically populated except for the State/Province (Region) field.

You may use the following address as a test:

6185 Taschereau Blvd, Brossard, Quebec J4Z 1A6

Please see the attached image for additional reference.

![issue](https://user-images.githubusercontent.com/90005739/142243060-164ba589-9e84-44f3-a3e0-e7c774159f08.png)

**Comment by PeterElkoShipperHQ** [comment]
Hi @michaelmagemontreal 

Thank you for contacting us regarding Quebec addresses not filling in the State/Province field. We are investigating this and will let you know once we have more information.

**Comment by wsajosh** [comment]
Thanks for raising this. Its fixed in the upcoming release
