### ISSUE TITLE
Issue with magento/composer-dependency-version-audit-plugin

### ISSUE THREAD

**Issue by Green2Matter** [shipperhq/module-address-autocomplete#35]
I've tried autocomplete module but I encountered issues with composer-dependency-version-audit-plugin
```
[Exception]                                                                                                                                    
  Higher matching version 20.5.0 of shipperhq/module-address-autocomplete was found in public repository packagist.org                           
                               than 20.4.0 in private https://repo.magento.com. Public package might've been taken over by a malicious entity,   
                               please investigate and update package requirement to match the version from the private repository
```  
Plus total fail when using `composer update` as described in:
[https://github.com/magento/magento2/issues/34390#issuecomment-988710259](https://github.com/magento/magento2/issues/34390#issuecomment-988710259)

**Comment by PeterElkoShipperHQ** [comment]
Hi @Green2Matter,
Thank you for contacting us regarding this issue with installing the autocomplete module. We have seen this with the latest version of Magento. We have spoken with Magento and the offending module is optional and can be removed by running the below command.

composer remove magento/composer-dependency-version-audit-plugin

This will allow you to install the autocomplete module as expected.

**Comment by Green2Matter** [comment]
Hi @PeterElkoShipperHQ 
I know that module can be removed but it's like disabling safety feature. Can't you have same software versions on all repos?
I've tried to reinstall with following result (composer 2):
<img width="1042" alt="autocomplete failed installation" src="https://user-images.githubusercontent.com/71682684/145390780-5b49aa79-6681-46e6-a247-3d2fab5eea87.png">
