### ISSUE TITLE
Logged in customer entering a new shipping address at checkout

### ISSUE THREAD

**Issue by purvid0204** [shipperhq/module-address-autocomplete#36]
Logged in customer entering a new shipping address at checkout functionality is not working when customer is login.

**Comment by PeterElkoShipperHQ** [comment]
@purvid0204
Hi, I'm Peter, a support engineer here at ShipperHQ. I did some testing on my own Magento 2 store running the Luma theme and do not experience any issues with a logged in customer.

I created a new customer and entered a default address.
I then added a product to my cart and clicked Checkout.
From there I used the +New Address button to enter a new address.
When entering this new address, I receive address suggestions as I expect from autocomplete.

I did this testing with versions 20.4.0 and 20.5.0 of the module on version 2.4.3 of Magento 

Are you experiencing an issue in a different part of the system? If not, please test this on a clean installation of Magento 2 and provide me with steps to reproduce the issue. 

Please let me know if you have any further questions.

I hope you have a great night!

**Comment by wsajosh** [comment]
Closing issue due to lack of response. Please reopen if the issue persists
