### ISSUE TITLE
Address of CA not fill in field city

### ISSUE THREAD

**Issue by PQT0604** [shipperhq/module-address-autocomplete#38]
I have address : 6000 Chemin de la Côte-des-Neiges not fill in city : "Montreal"

**Comment by wsadasmit** [comment]
Hi @PQT0604,

Thanks for raising this issue, we'll look into it and reply with what we determine. Talk to you soon,

**Comment by PQT0604** [comment]
Hi @wsadasmit i have fixed it , just clear city = " " at module-address-autocomplete/tree/main/src/view/frontend/web/js)/autocomplete.js
 138   else if (addressType === 'locality'') {

**Comment by PQT0604** [comment]
And Region fill in you can update this code for region of CA
 if(region.match("Yukon")){region="Yukon Territory"}
 if (region === "Québec" || region === "QC" || region === "QueBec"){region="Quebec"}

**Comment by wsajosh** [comment]
Hi @PQT0604 thanks for raising this. We've just released a new version which addresses this issue. Please update
