### ISSUE TITLE
Autocomplete Never Binds to Billing Address Street under Payment method

### ISSUE THREAD

**Issue by jmonschke** [shipperhq/module-address-autocomplete#6]
Autocomplete.js simply looks for the shipping address to handle autocompletion of the addresses. If you need to setup a separate billing address, it does not work. 

When binding to the autocomplete fields, it looks at `uiRegistry.get('checkout.steps.shipping-step.shippingAddress.shipping-address-fieldset.street').elems()[0]` instead of also checking for the billing address one.

**Comment by wsakaren** [comment]
It does not currently support this scenario. If you wish to create a PR feel free to do so otherwise I'll ask it to be added as a feature request. I can see the need just need to schedule it in as we don't have customers asking for at present (and its free/open).

**Comment by wsakaren** [comment]
https://webshopapps.atlassian.net/browse/SHQ16-2327

**Comment by wsakaren** [comment]
Internal JIRA - SHQ16-2327

**Comment by jmonschke** [comment]
#7 should take care of this.

**Comment by wsagen** [comment]
Closing as we are tracking internally as a feature request. PR was closed as not functioning
