### ISSUE TITLE
Invalid block type error in cart after enabling shipperhq extension.

### ISSUE THREAD

**Issue by vineeth030** [shipperhq/module-address-autocomplete#8]
I tried clearing cache, removing files in var/cache/*,var/generation/*,var/view_preprocessed/*,var/di/*. But still, I'm getting this issue when I reload my cart page. When I disable this module everything is back to normal. This a very useful extension for my project, it would be great if someone could help out me to fix this.
![ss-oct-19-n-1](https://user-images.githubusercontent.com/3368362/31763188-2d39bb8c-b4db-11e7-88a7-7604c9b58688.png)

**Comment by wsajason** [comment]
Hi. It sounds like there are missing or unreadable files in the installation. You'll need to ensure that [module-shipper ](https://github.com/shipperhq/module-shipper)is also installed on the site as it is a prerequisite for module-address-autocomplete.

**Comment by vineeth030** [comment]
Thanks a lot @wsajason 
I didn't know module-shipper is a prerequisite for module-address-autocomplete. Installation went fine this time.
